### ISSUE TITLE
Not found

### ISSUE THREAD

**Issue by timjm25** [shreyaskarnik/PubMedLDA#1]
I tried running the algorithm after making sure all of the libraries were setup correctly and got the following error. I was wondering what I should do to fix it.

Thanks in advance.

File "<pyshell#3>", line 1, in <module>
    getpmAbstracts.py -q [oncology] -o [PM_Oncology] -s [--s]
NameError: name 'getpmAbstracts' is not defined

**Comment by shreyaskarnik** [comment]
Hi @timjm25 are you in the working directory where the project is cloned?

**Comment by timjm25** [comment]
Yes but I put it in the folder for python 3.x. Should I copy the two python files and put them in a specific directory?

Thanks!

**Comment by shreyaskarnik** [comment]
I have not tested this code with Python 3.x, assuming you have the code somewhere in a folder `/tmp/` following command `python getpmAbstracts.py -q oncology -o output_oc  -s` should work.

**Comment by timjm25** [comment]
Ok great thanks!

**Comment by timjm25** [comment]
It's a nice piece of code too!
