### ISSUE TITLE
Reload not found

### ISSUE THREAD

**Issue by timjm25** [shreyaskarnik/PubMedLDA#2]
OK its running, but there's another error in python 3.

 File "getpmAbstracts.py", line 17, in <module>
    reload(sys)
NameError: name 'reload' is not defined

**Comment by shreyaskarnik** [comment]
This is Python 2.x specific please feel free to comment this line and try. Also over this weekend I will test this code with Python 3 and update accordingly.

**Comment by timjm25** [comment]
Great thank you so much for your help.

**Comment by timjm25** [comment]
It worked in Python V 3.X. I commented out both sys lines and it ran in seconds.

Thank you.
